language: python
python:
- "3.6"
env:
- DJANGO=2.1.7
install:
- pip install pipenv
- pipenv install --dev --system
script:
- python runtests.py
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: starwarsdemo